#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xDBD2CE893E2D1C87 (cfeck@kde.org)
#
Name     : lskat
Version  : 18.08.0
Release  : 2
URL      : https://download.kde.org/stable/applications/18.08.0/src/lskat-18.08.0.tar.xz
Source0  : https://download.kde.org/stable/applications/18.08.0/src/lskat-18.08.0.tar.xz
Source99 : https://download.kde.org/stable/applications/18.08.0/src/lskat-18.08.0.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : GFDL-1.2 GPL-2.0 LGPL-2.0
Requires: lskat-bin
Requires: lskat-data
Requires: lskat-license
Requires: lskat-locales
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : libkdegames-dev
BuildRequires : phonon-dev
BuildRequires : qtbase-dev qtbase-extras mesa-dev

%description
GENERAL NOTE:
https://games.kde.org/

%package bin
Summary: bin components for the lskat package.
Group: Binaries
Requires: lskat-data
Requires: lskat-license

%description bin
bin components for the lskat package.


%package data
Summary: data components for the lskat package.
Group: Data

%description data
data components for the lskat package.


%package doc
Summary: doc components for the lskat package.
Group: Documentation

%description doc
doc components for the lskat package.


%package license
Summary: license components for the lskat package.
Group: Default

%description license
license components for the lskat package.


%package locales
Summary: locales components for the lskat package.
Group: Default

%description locales
locales components for the lskat package.


%prep
%setup -q -n lskat-18.08.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1535434478
mkdir clr-build
pushd clr-build
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1535434478
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/lskat
cp COPYING %{buildroot}/usr/share/doc/lskat/COPYING
cp COPYING.DOC %{buildroot}/usr/share/doc/lskat/COPYING.DOC
cp COPYING.LIB %{buildroot}/usr/share/doc/lskat/COPYING.LIB
pushd clr-build
%make_install
popd
%find_lang lskat

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/lskat

%files data
%defattr(-,root,root,-)
/usr/share/applications/org.kde.lskat.desktop
/usr/share/icons/hicolor/128x128/apps/lskat.png
/usr/share/icons/hicolor/16x16/apps/lskat.png
/usr/share/icons/hicolor/22x22/apps/lskat.png
/usr/share/icons/hicolor/32x32/apps/lskat.png
/usr/share/icons/hicolor/48x48/apps/lskat.png
/usr/share/icons/hicolor/64x64/apps/lskat.png
/usr/share/kxmlgui5/lskat/lskatui.rc
/usr/share/lskat/grafix/blue.desktop
/usr/share/lskat/grafix/blue.rc
/usr/share/lskat/grafix/blue.svg
/usr/share/lskat/grafix/egyptian.desktop
/usr/share/lskat/grafix/egyptian.rc
/usr/share/lskat/grafix/egyptian.svg
/usr/share/lskat/grafix/oxygen.desktop
/usr/share/lskat/grafix/oxygen.rc
/usr/share/lskat/grafix/oxygen.svg
/usr/share/metainfo/org.kde.lskat.appdata.xml
/usr/share/xdg/lskat.categories

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/HTML/cs/lskat/index.cache.bz2
/usr/share/doc/HTML/cs/lskat/index.docbook
/usr/share/doc/HTML/de/lskat/index.cache.bz2
/usr/share/doc/HTML/de/lskat/index.docbook
/usr/share/doc/HTML/en/lskat/index.cache.bz2
/usr/share/doc/HTML/en/lskat/index.docbook
/usr/share/doc/HTML/en/lskat/lskat_screen_01.png
/usr/share/doc/HTML/es/lskat/index.cache.bz2
/usr/share/doc/HTML/es/lskat/index.docbook
/usr/share/doc/HTML/et/lskat/index.cache.bz2
/usr/share/doc/HTML/et/lskat/index.docbook
/usr/share/doc/HTML/fr/lskat/index.cache.bz2
/usr/share/doc/HTML/fr/lskat/index.docbook
/usr/share/doc/HTML/fr/lskat/lskat_screen_01.png
/usr/share/doc/HTML/it/lskat/index.cache.bz2
/usr/share/doc/HTML/it/lskat/index.docbook
/usr/share/doc/HTML/nl/lskat/index.cache.bz2
/usr/share/doc/HTML/nl/lskat/index.docbook
/usr/share/doc/HTML/pt/lskat/index.cache.bz2
/usr/share/doc/HTML/pt/lskat/index.docbook
/usr/share/doc/HTML/pt_BR/lskat/index.cache.bz2
/usr/share/doc/HTML/pt_BR/lskat/index.docbook
/usr/share/doc/HTML/ru/lskat/index.cache.bz2
/usr/share/doc/HTML/ru/lskat/index.docbook
/usr/share/doc/HTML/sv/lskat/index.cache.bz2
/usr/share/doc/HTML/sv/lskat/index.docbook
/usr/share/doc/HTML/uk/lskat/index.cache.bz2
/usr/share/doc/HTML/uk/lskat/index.docbook

%files license
%defattr(-,root,root,-)
/usr/share/doc/lskat/COPYING
/usr/share/doc/lskat/COPYING.DOC
/usr/share/doc/lskat/COPYING.LIB

%files locales -f lskat.lang
%defattr(-,root,root,-)

